### ISSUE TITLE
DocLibClient error on call of delete with Library parameter HTTP Error 500 -- Microsoft.SharePoint.SPQueryThrottledException

### ISSUE THREAD

**Issue by adelinor** [OfficeDev/Office-365-SDK-for-Java#20]
Past the issue #17, delete a folder or file with the method:

```java
ListenableFuture<Void> handle = this.client.delete(path, library);
```

fails with the error:

```
Caused by: java.lang.Exception: Invalid status code 500: {"error":{"code":"-2147024860, Microsoft.SharePoint.SPQueryThrottledException","message":{"lang":"en-US","value":"The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator."}}}

	at com.microsoft.services.sharepoint.OfficeClient$2.onSuccess(OfficeClient.java:195)
	at com.microsoft.services.sharepoint.OfficeClient$2.onSuccess(OfficeClient.java:181)
```

Using the endpoint suggested in the
[SharePoint REST reference document](https://msdn.microsoft.com/en-us/library/office/dn450841.aspx#bk_Folder)
works well, so why is this is not implemented in this library?

**Comment by hariso** [comment]
Just so that you don't waste your time here: https://github.com/OfficeDev/Office-365-SDK-for-Java/issues/1

**Comment by adelinor** [comment]
#1 does not answer anything sadly.

**Comment by hariso** [comment]
You can consider this project abandoned.: ) I too wanted to use it, but after I read through comments on #1, and saw the (in)activity on all the other tickets, I just left this.

**Comment by adelinor** [comment]
This project is a good starting point to use the SharePoint online API from a Java implementation so I will keep raising issues a I find them.
